### ISSUE TITLE
fix all error responses to correctly return a type

### ISSUE THREAD

**Issue by JackLewis-digirati** [dlcs/iiif-presentation#177] opened 2024-11-21 10:44 UTC
Some responses do not correctly return a `type` on an error response. This ticket is to fix this issue.

Some locations this occurs:

https://github.com/dlcs/iiif-presentation/blob/3bace7eafb528ced1a62e3aab3e040c44ae58954/src/IIIFPresentation/API/Infrastructure/ControllerBaseX.cs#L60

`WriteResult.NotFound`, `WriteResult.FailedValidation` and `WriteResult.StorageLimitExceeded` do not pass through a `type` to `PresentationProblem`

https://github.com/dlcs/iiif-presentation/blob/3bace7eafb528ced1a62e3aab3e040c44ae58954/src/IIIFPresentation/API/Infrastructure/ControllerBaseX.cs#L90

uses `controller.Problem`, which doesn't take a `type`

additionally, `controller.PresentationProblem` should be updated to take a mandatory `type` and the `type` parameter should be updated to accept a `Uri` instead of a `string`

this should resolve #176

**Comment by donaldgray** [comment] 2024-11-21 17:39
Duplicate of #176

**Closed by donaldgray** 2024-11-21 17:39 UTC
Labels: bug
